require 'yopta_switcher/version'
require 'yopta_switcher/selenium_driver_adapter'
require 'yopta_switcher/client'
require 'yopta_switcher/operations/turn_on'
require 'yopta_switcher/operations/turn_off'
